config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match '/signin' => 'sessions#create', :via => [:post], :as => 'sessions_create'
  match '/signin' => 'sessions#new', :via => [:get], :as => 'sessions_signin'
  match '/signout' => 'sessions#destroy', :via => [:get], :as => 'sessions_signout'
  match '/' => 'contests#dashboard', :via => [:get], :as => 'contests_dashboard'
  match '/leaderboard' => 'contests#leaderboard', :via => [:get], :as => 'contests_leaderboard'
  match '/signup' => 'contests#signup', :via => [:get], :as => 'contests_signup'
  post 'contests/create'
  post 'contests/validate'
  
  match '/:id' => 'contests#index', :via => [:get]
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  before_save { |account| account.email = email.strip.downcase }	
  before_save { |account| account.name = name.strip }
  before_save :create_remember_token
  before_save :initialize_level
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50, minimum: 6 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
  			uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def initialize_level
    self.level = 1
  end  

  private :create_remember_token, :initialize_level
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :account
  belongs_to :problem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include ProblemsHelper
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :sign_in_user, :only => [:index, :validate, :success]
  def index
    # Not started
    # render 'notstarted'
    # End of Not started

    # Ended
    render 'ended'
    # End of Ended
    
    if get_level > max_level
      flash[:success] = "Congrats! You cleared the problem set."
      render 'success'      
    else
      @name = Problem.find_by_level(get_level).url
      @problem = Problem.new
    end
  end

  def validate
    @answer = Problem.find_by_level(get_level).answer.split.join.downcase
    if @answer == params[:problem][:answer].split.join.downcase
      Account.where(:id => get_account_id).update_all(level: get_level+1, time: DateTime.now )
      flash[:success] = "Well done! Nailed it!"
    else
      flash[:danger] = "Ohh! nice try. Try again!!"
    end
    redirect_to "/"
  end

  def create
    require 'net/http'
  	@account = Account.new(account_params)
  	if verify_recaptcha(model: @account) && @account.save
  		redirect_to sessions_signin_path
  	else
  		render 'signup'
  	end
  end

  def leaderboard
    @accounts = Account.select(:name, :level, :college, :time).order(level: :desc, time: :asc)
    @max_level = max_level
  end

  def signup
  	@account = Account.new
  end

  def account_params
  	params.require(:account).permit(:name, :email, :college, :register_number, :department, :year, :phone, :password, :password_confirmation)	
  end

  private :account_params
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	account = Account.find_by_email(params[:session][:email])
  	if account and account.authenticate(params[:session][:password])
  		sign_in account
  		flash[:success] = "Login success!"
      redirect_to contests_index_path
  	else
  		flash[:danger] = "Oh snap! Invalid username or password"
  		render 'new'
  	end
  end

  def new
    if signed_in?
      flash[:danger] = "You were already signed in!"
      redirect_to contests_index_path
    end
  	@current_account = nil
  end

  def destroy
  	sign_out
  	redirect_to contests_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
	def max_level
		return Problem.maximum(:level)
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(account)
		cookies.permanent[:remember_token] = account.remember_token
		self.current_account = account
	end

	def sign_in_user
		unless signed_in?
	        flash[:danger] = "Please log in."
	        redirect_to sessions_signin_url
	    end
	end

	def sign_out
		cookies.delete(:remember_token)
		self.current_account = nil
	end
	
	def signed_in?
		!current_account.nil?
	end
	
	def current_account=(account)
		@current_account = account
	end

	def current_account
		@current_account = Account.find_by_remember_token(cookies[:remember_token])
	end

	def get_name
		@current_account.name
	end

	def get_account_id
		@current_account.id.to_i
	end

	def get_level
		if @current_account.nil?
			current_account
		end
		@current_account.level
	end

	def get_problem_id
		level = get_level
		if level > max_level
			level = max_level
		end
		Problem.where(level: level).select(:id).first.id.to_i
	end
end

app/views/contests/dashboard.html.erb
<% content_for :title, "Dashboard" %>
<div class="container container-table">
    <div class="row vertical-center-row">
        <div class="text-center col-md-4 col-md-offset-4">
        	<div>
				<table class="table table-striped">
				  <thead>
				    <tr>
				      <th>#</th>
				      <th class="text-center">Problem Name</th>
				    </tr>
				  </thead>
				  <tbody>
					<% @problems.each_with_index do |problem, index| %>
				    	<% if signed_in? and problem.level < get_level %>
				    		<tr class="success">
				    	<% else %>
				    		<tr>
				    	<% end %>
				    		<th scope="row"><%= index+1 %></th>
				    		<% if signed_in? and problem.level <= get_level %>
				    			<td><%= link_to problem.url, "/"+problem.id.to_s %></td>
			    			<% else %>
			    				<td><%= problem.url %></td>
							<% end %>
				    	</tr>	
					<% end %>    	
				  </tbody>
				</table>
			</div>
        </div>
    </div>
</div>

app/views/contests/ended.html.erb
<% content_for :title, "Oh! Contest Ended" %>
<div class="row">
	<div class="panel panel-danger">
	  <div class="panel-body">
	    Treasure Hunt - Oop, contest ended!
	  </div>
	  <div class="panel-footer">
	  	The contest Ended! <br>
	  	For more information check our <a href="https://www.facebook.com/trigger.mit/">facebook - trigger</a> page. <br>
	  	or our website <a href="http://www.trigger.act.mitindia.edu">Trigger' 16</a>.
	  </div>
	</div>
</div>

app/views/contests/index.html.erb
<% content_for :title, "Contest" %>
<div class="row">
	<h3>Welcome to Level <%= get_level %></h3>
</div>
<div class="row">
	<div class="col-sm-offset-2 col-md-offset-2 col-lg-offset-2 col-sm-8 col-md-8 col-lg-8">
		<%= image_tag("#{@name}.jpg", :class => "img-responsive center-block") %>
	</div>
</div>
<div class="jumbotron">
	<%= form_for @problem, url: {action: "validate"} do |f| %>
		<fieldset>
			<%= render 'shared/error_messages', locals: { obj: @problem} %>
			<%= render 'shared/form_label_text', locals: { obj: f, label: "answer"} %>
			<%= render 'shared/form_submit', locals: { obj: f, type: "submit", reset: true} %>
		</fieldset>
	<% end %>
</div>

app/views/contests/leaderboard.html.erb
<% content_for :title, "Leaderboard" %>
<div>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>#</th>
	      <th>Name</th>
	      <th>College</th>
	      <th>Level</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @accounts.each_with_index do |account, index| %>
	    	<% if account.level > max_level %>
	    		<tr class="success">
	    	<% else %>
	    		<tr>
	    	<% end %>
	    		<th scope="row"><%= index+1 %></th>
	    		<td><%= account.name %></td>
	    		<td><%= account.college %></td>
	    		<td><%= account.level - 1  %></td>
	    	</tr>	
		<% end %>    	
	  </tbody>
	</table>
</div>

app/views/contests/notstarted.html.erb
<% content_for :title, "The world can wait!" %>
<div class="row">
	<div class="panel panel-success">
	  <div class="panel-body">
	    Treasure Hunt - The contest begins shortly!
	  </div>
	  <div class="panel-footer">
	  	The contest is not started yet! <br>
	  	For more information check our <a href="https://www.facebook.com/trigger.mit/">facebook - trigger</a> page. <br>
	  	or our website <a href="http://www.trigger.act.mitindia.edu">Trigger' 16</a>.
	  </div>
	</div>
</div>

app/views/contests/signup.html.erb
<% content_for :title, "Sign Up" %>
<div class="jumbotron">
	<fieldset>
        <legend>Sign Up</legend>
	<%= form_for @account, url: {action: "create"} do |f| %>
		<%= render 'shared/error_messages', locals: { obj: @account} %>
		<%= render 'shared/form_label_text', locals: { label: "name", obj: f } %>
		<%= render 'shared/form_label_email', locals: { label: "email", obj: f } %>
		<%= render 'shared/form_label_text', locals: { label: "college", obj: f} %>
		<%= render 'shared/form_label_text', locals: { label: "register_number", obj: f} %>
		<%= render 'shared/form_label_text', locals: { label: "department", obj: f} %>
		<%= render 'shared/form_label_text', locals: { label: "year", obj: f} %>
		<%= render 'shared/form_label_text', locals: { label: "phone", obj: f} %>
		<%= render 'shared/form_label_password', locals: { label: "password", obj: f} %>
		<%= render 'shared/form_label_password', locals: { label: "password_confirmation", obj: f} %>
		<div class="form-group row">
			<div class="col-sm-offset-2 col-sm-10">
				<%= recaptcha_tags %>
			</div>
		</div>
		<%= render 'shared/form_submit', locals: { obj: f, type: "submit", reset: true} %>
	</fieldset>
	<% end %>
</div>

app/views/contests/success.html.erb
<% content_for :title, "Congrats!" %>
<div class="row">
	<div class="col-sm-offset-4 col-md-offset-4 col-lg-offset-4 col-sm-4 col-md-4 col-lg-4">
		<%= image_tag("success.jpg", :class => "img-responsive center-block") %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Bootstrap href -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!-- End of Bootstrap -->
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Start of Navigation Bar -->
	<%= render 'shared/header' %>
<!-- End of Navigation Bar -->


<div class="container">
  <!-- Render flash partial -->
  <%= render 'shared/flash' %>
  <!-- End of flash -->
	<%= yield %>
</div>

<% if Rails.env.development? %>
	<%= debug(params) %>
<% end %>

</body>
</html>

app/views/problems/show.html.erb
<h1>Problems#show</h1>
<p>Find me in app/views/problems/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if locals[:obj].errors.any? %>
	<div  class="alert alert-danger" role="alert">
		<div>
			<%= pluralize(locals[:obj].errors.count, "error") %> prohibited this form from being saved.
		</div>
		<ul>
			<% locals[:obj].errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
	<% if name.strip == "recaptcha_error" %>
		<% next %>
	<% end %>
    <%= content_tag :div, msg.to_s, class: "alert alert-#{name}" %>
<% end %>

app/views/shared/_form_label_email.html.erb
<div class="form-group row">
	<%= locals[:obj].label locals[:label], class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-10">
		<%= locals[:obj].email_field locals[:label], class: 'form-control', placeholder: "#{locals[:label]}" %>
	</div>
</div>

app/views/shared/_form_label_password.html.erb
<div class="form-group row">
	<%= locals[:obj].label locals[:label], class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-10">
		<%= locals[:obj].password_field locals[:label], class: 'form-control', placeholder: "#{locals[:label]}" %>
	</div>
</div>

app/views/shared/_form_label_text.html.erb
<div class="form-group row">
	<%= locals[:obj].label locals[:label], class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-10">
		<%= locals[:obj].text_field locals[:label], class: 'form-control', placeholder: "#{locals[:label]}" %>
	</div>
</div>

app/views/shared/_form_submit.html.erb
<div class="form-group row">
	<div class="col-sm-offset-2 col-sm-10">
		<%= locals[:obj].submit "Submit", class: 'btn btn-primary' %>
		<% if locals[:reset] %>
			<%= locals[:obj].submit "Reset", :type => "reset", class: 'btn btn-secondary' %>
		<% end %>
	</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Trigger 2K16 - Treasure Hunt", contests_index_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Leaderboard", contests_leaderboard_path %></li>
        <% if signed_in? %>
        	<li><%= link_to get_name, contests_index_path %></li>
          <li><%= link_to "Signout", sessions_signout_path %></li>
        <% else %>
	        <li><%= link_to "Login", sessions_signin_path %></li>
	        <li><%= link_to "Signup", contests_signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>